### PR TITLE
this adds meta & meta propchecking

### PR DESCRIPTION
**Pull request by pnispel**
#### Summary
FSA specifies the `meta` tag that should sit beside the payload. this PR adds the ability to specify a `meta` object in the action creator call that will end up beside the `payload` object in the reducer. 

#### Example
```
export const { actions, reducer, constants } = createModule({
  name: 'foo',
  transformations: [
    {
      action: 'FETCH',
      payloadTypes: {
        id: oneOfType([string, number]),
      },
      metaTypes: {
        foo: string
      },
      reducer: (state, {payload: {id}, meta: {foo}}) => {
        // foo === 'bar'
      },
    },
...
actions.fetch({id: 123, meta: {foo: 'bar'}});
```

The meta tag is only created if the metaTypes are specified.

#### Reading
https://github.com/acdlite/flux-standard-action
https://github.com/acdlite/redux-actions#createactiontype-payloadcreator--identity-metacreator `metaCreator`

### CODE REVIEW

**Comment by mboperator** [comment]
Awesome! Can we remove the `lib` folder from this branch to clean up the PR?

**Comment by pnispel** [comment]
👍

**Comment by mboperator** [comment]
How does `meta` get into the `action` object? Is it included when the action is invoked? eg: `this.props.actions.fetch({ id: 5 }, { metaAttr: 'something')`

**Comment by mboperator** [comment]
I'd rather we include meta attributes in the `transformation object` itself

**Comment by pnispel** [comment]
ooh. thats a good thought @mboperator

**Comment by pnispel** [comment]
[this pr](https://github.com/mboperator/redux-modules/pull/22) addresses the comment https://github.com/mboperator/redux-modules/pull/20#issuecomment-219585452

**Comment by pnispel** [comment]
@mboperator the one thing about that though: the use case I have for the meta tag is to use redux-optimistic-ui, where you specify a unique identifier in the meta tag that should be unique across groups of `SOME_ASYNC` `_SUCCESS` and `_ERROR` calls. I cant think of a way to do that while specifying the meta tag inside the transformations, while if we pass the meta tag through the action creator call its fairly simple to create a new identifier per async lifecycle

**Comment by pnispel** [comment]
I'm going to close this in favor of https://github.com/mboperator/redux-modules/pull/23

**Pull request closed without merging**
