### PR TITLE
connectModule dynamically builds reducer as needed

### PR DESCRIPTION
**Pull request by mboperator**
Addresses #31 

### API
```js
// Default Combiner is combineReducers from redux
const ModuleProvider = createModuleProvider();

// Custom Combiner (eg one from redux-immutable)
const ModuleProvider = createModuleProvider(reducers => {
  console.log('Injected reducer combiner');
  return combineReducers(reducers);
});

() => (
<ModuleProvider store={store}>
    <ConnectedComponent />
</ModuleProvider>
) 
```

### CODE REVIEW

**Comment by wtgtybhertgeghgtwtg** [comment]
If I'm reading `_collectReducers` in `connectModules.js` right, connectModules will always replace the reducer already in the store.
`combineReducers` will work for normal states, but won't you need the `redux-immutable` version for immutable states?

**Comment by mboperator** [comment]
@wtgtybhertgeghgtwtg You're correct, this branch is still in progress. I've implemented some code for memoizing modules previously recorded but I haven't gotten around to testing it yet.

So far I personally have only ever used the normal `combineReducer` with `immutable` state in the subtrees. I can research what it would take to get the entire state tree using immutable though ^^

**Comment by mboperator** [comment]
The bulk of the code can be found here: https://github.com/mboperator/redux-modules/pull/32/files#diff-677218d3916648c1438c88a76ea2c007R1

Sorry about the bad diff, I've just been copy pasta'ing the examples for now. I'll get around to DRYing them up soon

**Comment by wtgtybhertgeghgtwtg** [comment]
Ideally, using `immutablejs` or not should be a developer decision.  It limits the potential audience of the library if it only works one way or the other because this feature was internalized.
I believe a feature like this is outside of the scope of this library.

**Comment by mboperator** [comment]
I think if I move the `replaceReducer` logic up to a root level decorator it'll be fine. That way developers can choose whether to allow the automatic reducer building by including that decorator. Additionally that root level decorator can take a function to allow devs to override the existing `combineReducers` logic.

**Comment by wtgtybhertgeghgtwtg** [comment]
So, to be clear, this feature will be optional for the user?  In some cases, such as async routes, the user might not want, nor will they expect, the store to be mutated.

**Comment by mboperator** [comment]
Yeah, this will logic will move to a decorator that wraps the `redux` `Provider`.
As I work on this more with outside perspectives I'm starting to see that this makes huge assumptions about how the `rootReducer` is created. I'll probably hold off on this for a bit.

**Pull request merged**
